language: ruby
sudo: required
rvm:
  - 2.3.0
services:
  - postgresql
  - elasticsearch
addons:
  postgresql: "9.4"
before_install: 
  # Install a more recent version of elasticsearch, also couldn't find preinstaleld version 
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.5/elasticsearch-2.3.5.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.5.deb && sudo service elasticsearch restart
before_script:
  # The installation fails to create a scripts directory or copy the elasticsearch.yml
  # or logging.yml files over. THis fixes that.
  - sudo mkdir -p /usr/share/elasticsearch/config/scripts   
  - sudo cp /etc/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config
  - sudo cp /etc/elasticsearch/logging.yml /usr/share/elasticsearch/config
  - psql -c 'create database dms_test;' -U postgres
  - sleep 10 # To make sure Elasticsearch instance is ready
script: 
  - export RAILS_ENV=test
  - bundle exec rake db:create db:schema:load db:test:prepare
  - bundle exec rspec --tag slow   # we should run all the tests in CI
branches:
  only:
  - master
  - develop